import path from "node:path";
import fs from "node:fs";
import { fileURLToPath } from "node:url";
import { withMicrofrontends } from '@vercel/microfrontends/next/config';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Auto-generated by generate-routes.js from module definitions
const rewritesPath = path.join(__dirname, "src", "app", "rewrites.json");
const autoRewrites = fs.existsSync(rewritesPath)
  ? JSON.parse(fs.readFileSync(rewritesPath, "utf-8"))
  : [];

/** @type {import('next').NextConfig} */
const nextConfig = {
  turbopack: {
    root: __dirname,
  },
  onDemandEntries: {
    // Keep dev pages hot longer to avoid tab-switch recompiles that feel like reloads.
    maxInactiveAge: 60 * 60 * 1000,
    pagesBufferLength: 8,
  },
  async rewrites() {
    return autoRewrites;
  },
};

export default withMicrofrontends(nextConfig);
